name: ROS Qt Creator plugin build and archive release

on: [push]

jobs:
  build:
    name: build (${{ matrix.config.name }})
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
          - { name: "Linux", os: ubuntu-latest }
          # - { name: "Windows", os: windows-latest }
          # - { name: "macOS", os: macos-latest }
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v1
        with:
          python-version: "3.x"

      - uses: conda-incubator/setup-miniconda@v2
        if: runner.os == 'Windows'

      - name: install Linux system dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt update
          sudo apt install libgl1-mesa-dev ninja-build libyaml-cpp-dev libqtermwidget5-0-dev libutf8proc-dev libboost-dev

      - name: install Windows system dependencies
        if: runner.os == 'Windows'
        run: |
          choco install ninja
          conda install -c conda-forge yaml-cpp

      - name: install macOS system dependencies
        if: runner.os == 'macOS'
        run: brew install ninja yaml-cpp

      - name: install Qt and Qt Creator
        shell: bash # set bash (on Windows) to pipe into $GITHUB_ENV
        run: |
          pip install pyyaml requests py7zr
          python setup.py --export_variables
          cat env >> $GITHUB_ENV

      - name: build plugin
        run: |
          cmake -B build -GNinja -DCMAKE_PREFIX_PATH=${{ env.QTC_PREFIX_PATH }}
          cmake --build build --target package

      - name: find plugin archive
        shell: bash
        run: |
          find build/ -maxdepth 1 -name 'ROSProjectManager-*-*-*.zip' -printf "%f" > archive_name
          echo "QTC_PLUGIN_ARCHIVE=`cat ./archive_name`" >> $GITHUB_ENV

      # upload the archive file and the text file with the archive name as single "ci_plugin_archive"
      - name: upload archive release artifact
        uses: actions/upload-artifact@v2
        with:
          name: ci_plugin_archive
          path: |
            ./archive_name
            ./build/${{ env.QTC_PLUGIN_ARCHIVE }}

  release:
    name: release plugin archive
    if: contains(github.ref, '/tags/')
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: create release
        uses: actions/create-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: false
          prerelease: false

      # download the single "ci_plugin_archive" and extract the archive and the file with the archive name
      - uses: actions/download-artifact@v2
        with:
          name: ci_plugin_archive
          path: ./

      - name: set archive name
        run: |
          echo "QTC_PLUGIN_ARCHIVE=`cat ./archive_name`" >> $GITHUB_ENV

      - name: upload release artifacts
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/${{ env.QTC_PLUGIN_ARCHIVE }}
          asset_name: ${{ env.QTC_PLUGIN_ARCHIVE }}
          asset_content_type: application/zip
